import { generateImage } from "../src/ai/images/minimax";
import * as fs from "node:fs";
import * as path from "node:path";

const OUTPUT_DIR = "public/images/new-gallery";

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const images = [
  // Europe (10)
  { slug: "sweden-stockholm", title: "Stockholm Old Town", prompt: "Stockholm Old Town Gamla Stan in Sweden completely empty of people, bright clear sunny Scandinavian midday with crystal blue sky, the charming medieval cobblestone streets with colorful historic buildings in red yellow and orange, a stone plaza or marked position where visitors normally stand for photos but currently empty, the famous narrow alleyways and historic squares, the Swedish parliament building visible on the hill across the water, the Baltic Sea inlet surrounding the island old town, crisp Nordic sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "denmark-nyhavn", title: "Nyhavn Copenhagen", prompt: "Nyhavn historic harbor in Copenhagen Denmark completely empty of people, bright clear sunny Danish midday with crystal blue sky, the iconic colorful 17th century waterfront buildings in yellow orange red and blue reflecting in the calm canal water, a stone quayside or marked position where tourists normally stand for photos but currently empty, historic wooden ships and sailboats moored along the canal, the charming Danish waterfront architecture, warm Scandinavian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "croatia-dubrovnik", title: "Dubrovnik Old Town", prompt: "Dubrovnik Old Town and city walls in Croatia completely empty of people, bright clear sunny Mediterranean midday with crystal blue Adriatic Sea sky, the famous medieval stone walls and forts rising from the turquoise sea, a stone fort platform or marked position where visitors normally stand for photos but currently empty, the orange-roofed historic city visible above the walls, the Adriatic coastline with ferries and islands in the distance, brilliant Mediterranean sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "hungary-budapest", title: "Budapest Parliament", prompt: "Hungarian Parliament Building on the Danube River in Budapest completely empty of people, bright clear sunny Hungarian midday with crystal blue sky, the famous Gothic Revival palace with its iconic green copper domes and 96 meter tall spire, a riverside platform or marked position where visitors normally stand for photos but currently empty, the Danube flowing past with the Buda Castle visible on the opposite bank, the historic Hungarian government building with thousands of windows, warm Central European sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "slovenia-lake-bled", title: "Lake Bled", prompt: "Lake Bled in Slovenia completely empty of people, bright clear sunny Alpine midday with crystal blue sky, the famous emerald green lake with the tiny island and Church of St Mary visible at its center, a wooden lakeside platform or marked position where visitors normally stand for photos but currently empty, the medieval Bled Castle perched on the cliffs above the lake, the dramatic Julian Alps rising in the background, the iconic church bell tower with its baroque spire, Lake Bled castle on the cliff, warm Alpine sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "romania-bran-castle", title: "Bran Castle", prompt: "Bran Castle also known as Dracula Castle in Transylvania Romania completely empty of people, bright clear sunny Romanian midday with crystal blue sky, the famous medieval fortress with its gray stone walls and towers perched on a cliff between two mountain peaks, a mountain clearing or marked position where visitors normally stand for photos but currently empty, the dramatic Carpathian Mountains surrounding the castle, the fortified castle with its defensive walls and watchtowers, the Romanian mountain landscape, warm Eastern European sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "bulgaria-rila-monastery", title: "Rila Monastery", prompt: "Rila Monastery in Bulgaria completely empty of people, bright clear sunny Bulgarian midday with crystal blue sky, the famous Eastern Orthodox monastery with its distinctive striped arches and domes rising from the forested mountain valley, a stone courtyard or marked position where visitors normally stand for photos but currently empty, the massive medieval monastery complex with its high stone walls, the surrounding Rila Mountains and pine forest, the central church with its golden domes and elaborate frescoes, dramatic mountain monastery architecture, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "latvia-riga", title: "Riga Old Town", prompt: "Riga Old Town in Latvia completely empty of people, bright clear sunny Baltic midday with crystal blue sky, the famous Art Nouveau buildings and medieval architecture lining the cobblestone streets, a town square or marked position where visitors normally stand for photos but currently empty, the iconic House of the Blackheads and St Peters Church spire visible, the charming Baltic European old town with its varied architectural styles, the Daugava River flowing past the historic district, cool Baltic sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "estonia-tallinn", title: "Tallinn Old Town", prompt: "Tallinn Old Town in Estonia completely empty of people, bright clear sunny Baltic midday with crystal blue sky, the famous medieval town with its cobblestone streets and historic merchant houses in red and yellow, a town square or marked position where visitors normally stand for photos but currently empty, the iconic Alexander Nevsky Cathedral with its onion domes and the Town Hall Tower visible above the rooftops, the charming medieval Baltic old town walls and towers, Toompea Hill with its cathedral, the Baltic Sea visible in the distance, crisp Nordic light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "malta-valletta", title: "Valletta Waterfront", prompt: "Valletta waterfront and harbor in Malta completely empty of people, bright clear sunny Mediterranean midday with crystal blue sky, the famous Golden Bay and the historic Fort St. Elmo on the peninsula, a terrace platform or marked position where visitors normally stand for photos but currently empty, the massive stone fortifications and bastions of the UNESCO listed city, the Mediterranean harbor with cruise ships and traditional boats, the charming Maltese architecture in warm honey colored stone, brilliant island sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },

  // Southeast Asia (8)
  { slug: "cambodia-angkor-wat", title: "Angkor Wat", prompt: "Angkor Wat temple in Cambodia completely empty of people, bright clear sunny Southeast Asian midday with crystal blue tropical sky, the famous massive temple complex with its iconic five towers and intricate stone carvings reflected in the surrounding moat, a stone pathway or marked position where visitors normally stand for photos but currently empty, the largest religious monument in the world with its lotus and tower architecture, the ancient Khmer Empire temple with galleries and bas-reliefs, the surrounding jungle visible in the distance, brilliant tropical sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "myanmar-shwedagon", title: "Shwedagon Pagoda", prompt: "Shwedagon Pagoda in Yangon Myanmar completely empty of people, bright clear sunny Southeast Asian midday with crystal blue sky, the famous massive golden Buddhist stupa rising 98 meters with its diamond orb and parasol covered in real gold plates, a stone terrace or marked position where visitors normally circumambulate for photos but currently empty, the elaborate gold and jeweled decoration of the stupa, the surrounding smaller temples and shrines, the tropical Burmese city visible beyond the temple complex, brilliant golden Myanmar sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "malaysia-petronas", title: "Petronas Twin Towers", prompt: "Petronas Twin Towers in Kuala Lumpur Malaysia completely empty of people, bright clear sunny Southeast Asian midday with crystal blue tropical sky, the famous twin skyscrapers with their Islamic geometric steel and glass facade, a plaza fountain or marked position where visitors normally stand for photos but currently empty, the iconic 452 meter towers with the skybridge connecting them at level 41, the modern Malaysian cityscape surrounding the towers, the nearby KLCC park and fountain, brilliant tropical sunlight on the reflective facade, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "singapore-marina-bay", title: "Marina Bay Sands", prompt: "Marina Bay Sands resort in Singapore completely empty of people, bright clear sunny Southeast Asian midday with crystal blue tropical sky, the famous three towers with the massive ship-shaped rooftop infinity pool and SkyPark, a waterfront platform or marked position where visitors normally stand for photos but currently empty, the iconic integrated resort with its distinctive architecture, the Singapore Flyer giant wheel and the Merlion statue visible nearby, the harbor and city skyline reflected in the water, brilliant tropical sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "philippines-banaue", title: "Banaue Rice Terraces", prompt: "Banaue Rice Terraces in Ifugao Philippines completely empty of people, bright clear sunny Southeast Asian midday with crystal blue sky, the famous ancient mountain terraces carved into the Cordillera mountains resembling giant green staircases ascending into the clouds, a mountain path or marked position where visitors normally stand for photos but currently empty, the 2000 year old rice terraces stretching across the mountainside, the traditional Ifugao wooden huts and palm trees visible, the dramatic mountain landscape of the Philippine Cordillera, brilliant tropical mountain sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "southkorea-gyeongbokgung", title: "Gyeongbokgung Palace", prompt: "Gyeongbokgung Palace in Seoul South Korea completely empty of people, bright clear sunny Korean midday with crystal blue sky, the famous Joseon Dynasty palace with its iconic red and green traditional Korean architecture and the massive Geunjeongjeon main hall, a palace courtyard or marked position where visitors normally stand for photos but currently empty, the traditional Korean palace buildings with their curved eaves and dancheong painted columns, the Bukchon Hanok village visible in the background beyond the palace walls, the National Folk Museum and mountains of Seoul, warm Korean traditional sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "taiwan-taipei-101", title: "Taipei 101", prompt: "Taipei 101 building in Taiwan completely empty of people, bright clear sunny Southeast Asian midday with crystal blue sky, the famous 508 meter skyscraper with its distinctive Chinese pagoda-style architecture and the massive tuned mass damper visible, a plaza platform or marked position where visitors normally stand for photos but currently empty, the world's tallest green building with its sectioned setbacks and traditional Chinese symbolism, the Xinyi District shopping area and Taipei city visible below, the massive bamboo sprout design of the tower, brilliant tropical sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "hongkong-victoria-peak", title: "Victoria Peak", prompt: "Victoria Peak also known as The Peak in Hong Kong completely empty of people, bright clear sunny Southeast Asian midday with crystal blue sky, the famous viewing platform with its traditionalPeak Tower building and the entire Hong Kong skyline spread out below, a marked viewing platform or position where visitors normally stand for photos but currently empty, the spectacular panorama of Hong Kong harbor with its skyscrapers and the iconic buildings of Central, the Hong Kong Island coastline and Victoria Harbour filled with boats and ships, the dramatic mountain and sea backdrop, the Peak Tram station visible, brilliant Asian harbor light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },

  // Middle East (7)
  { slug: "macau-ruins-st-paul", title: "Ruins of St. Paul's", prompt: "Ruins of St. Pauls in Macau completely empty of people, bright clear sunny Southeast Asian midday with crystal blue sky, the famous stone facade of the 17th century Portuguese church remaining after a fire destroyed the rest of the building, a plaza or marked position where visitors normally stand for photos but currently empty, the intricate baroque stone carvings and religious figures visible on the facade, the 68 steps leading up to the church, the backdrop of modern Macau buildings and the famous Macau Tower, the colonial Portuguese and Chinese mix of architecture, brilliant Macau sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "israel-jerusalem", title: "Dome of the Rock", prompt: "Dome of the Rock on the Temple Mount in Jerusalem completely empty of people, bright clear sunny Middle Eastern midday with crystal blue sky, the famous golden dome and octagonal Islamic shrine rising above the Old City walls, a viewing platform or marked position where visitors normally stand for photos but currently empty, the iconic ancient shrine with its Byzantine and Islamic architecture, the Old City walls and the dome of the Church of the Holy Sepulchre visible below, the Western Wall plaza in the distance, the sacred Old City of Jerusalem spread out below, brilliant Middle Eastern sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "saudi-riyadh", title: "Kingdom Centre Tower", prompt: "Kingdom Centre Tower in Riyadh Saudi Arabia completely empty of people, bright clear sunny Arabian midday with crystal blue desert sky, the famous modern skyscraper with its distinctive parabolic arch design and the Sky Bridge connecting the two towers, a mall plaza or marked position where visitors normally stand for photos but currently empty, the iconic symbol of modern Riyadh with its reflective glass facade, the surrounding modern Saudi capital city with other buildings, the vast Arabian desert visible beyond the city, brilliant desert sunlight on the towers, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "qatar-doha", title: "Museum of Islamic Art", prompt: "Museum of Islamic Art in Doha Qatar completely empty of people, bright clear sunny Arabian midday with crystal blue Persian Gulf sky, the famous modern museum building with its iconic geometric design inspired by ancient Islamic architecture rising from the waterfront, a promenade platform or marked position where visitors normally stand for photos but currently empty, the stunning five-story building with its stacked cubes and stone facade, the Doha Corniche waterfront with the Persian Gulf visible beyond, the modern Qatari cityscape rising behind the museum, brilliant desert sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "lebanon-bcharre", title: "Cedars of God", prompt: "The ancient Cedars of God forest in Bcharre Lebanon completely empty of people, bright clear sunny Lebanese midday with crystal blue Mediterranean sky, the famous grove of millennia-old Lebanon cedar trees with their spreading dark green branches, a forest clearing or marked position where visitors normally stand for photos but currently empty, the 4000 year old cedar trees with their massive trunks and distinctive horizontal layers, the mountain landscape of the Lebanese Cedar Forest Reserve, snow visible on the peaks of the surrounding Qadisha Valley mountains, the ancient spiritual forest, cool mountain Mediterranean light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "oman-muscat", title: "Sultan Qaboos Grand Mosque", prompt: "Sultan Qaboos Grand Mosque in Muscat Oman completely empty of people, bright clear sunny Arabian midday with crystal blue sky, the famous massive white marble mosque with its single large golden dome and 50 meter tall minarets, a mosque courtyard or marked position where visitors normally stand for photos but currently empty, the stunning Islamic architecture with its intricate geometric patterns and hand-woven Persian carpet inside, the white marble walls and floors gleaming in the desert sun, the manicured gardens surrounding the mosque, the Omani capital city visible beyond, brilliant desert mosque light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "bahrain-manama", title: "Bahrain World Trade Center", prompt: "Bahrain World Trade Center in Manama completely empty of people, bright clear sunny Arabian midday with crystal blue Persian Gulf sky, the famous twin tower skyscraper with its distinctive sail-shaped bridges connecting the buildings, a waterfront plaza or marked position where visitors normally stand for photos but currently empty, the iconic sail-shaped wind turbines between the towers generating clean energy, the modern Bahraini financial district surrounding the towers, the Persian Gulf waters and Manama skyline, brilliant desert coastal sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },

  // Central Asia & Caucasus (5)
  { slug: "georgia-tbilisi", title: "Narikala Fortress", prompt: "Narikala Fortress overlooking old Tbilisi in Georgia completely empty of people, bright clear sunny Caucasian midday with crystal blue sky, the ancient 4th century Persian citadel and walls rising from the hillside above the old city, a hillside viewing platform or marked position where visitors normally stand for photos but currently empty, the dramatic fortress ruins with its Persian and Georgian architecture, the colorful traditional houses and balconies of the old town below, the Metekhi Church and the modern city visible beyond, the Kura River winding through the valley, the iconic silhouette of the fortress above Tbilisi, warm Caucasian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "armenia-sevan", title: "Lake Sevan", prompt: "Lake Sevan in Armenia completely empty of people, bright clear sunny Armenian midday with crystal blue sky, the famous large mountain lake known as the Blue Pearl of Armenia with the Sevanavank monastery on the peninsula, a lakeside promenade or marked position where visitors normally stand for photos but currently empty, the dramatic lake at 1900m elevation surrounded by the Gegham mountains, the historic Armenian church with its twin khachkars on the peninsula extending into the blue water, the remote and rugged Armenian highland landscape, Lake Sevans unique peninsula and medieval monastery, cool mountain lake air, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "azerbaijan-baku", title: "Heydar Aliyev Center", prompt: "Heydar Aliyev Center in Baku Azerbaijan completely empty of people, bright clear sunny Caspian midday with crystal blue sky, the famous futuristic museum and cultural center with its distinctive flowing white curves and smooth organic architecture, a plaza or marked position where visitors normally stand for photos but currently empty, the iconic building designed by Zaha Hadid with its seamless flowing lines resembling a river or mountain, the white exterior and glass surfaces reflecting the Caspian sky, the modern Azerbaijani capital city visible beyond, the Baku Flame Towers in the background, brilliant Caspian coastal light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "kazakhstan-almaty", title: "Kok Tobe TV Tower", prompt: "Kok Tobe hill with the famous TV tower in Almaty Kazakhstan completely empty of people, bright clear sunny Central Asian midday with crystal blue sky, the famous 250 meter tall tower and the giant aluminum statue of an eagle with a man visible on the hilltop, a marked viewing platform or position on the hill where visitors normally stand for photos but currently empty, the spectacular panoramic view of Almaty and the snow-capped Tian Shan mountains in the background, the cable car station and amusement park on the hill, the ancient apple city spread below, the dramatic mountain backdrop, cool Central Asian alpine light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
  { slug: "uzbekistan-samarkand", title: "Registan Square", prompt: "Registan Square in Samarkand Uzbekistan completely empty of people, bright clear sunny Central Asian midday with crystal blue sky, the famous ancient plaza with the three magnificent madrassas with their tile-covered facades in blue and gold, a stone plaza or marked position where visitors normally stand for photos but currently empty, the iconic Islamic architecture of Ulugh Beg Madrasa Sher Dor Madrasa and Tilya Kori Madrasa with their minarets and domes, the stunning mosaic tiles and calligraphic inscriptions, the ancient Silk Road city of Samarkand, the historic square surrounded by the old city, brilliant Central Asian sunlight on the tile facades, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans" },
];

async function downloadImage(url: string, filepath: string): Promise<void> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download image: ${response.statusText}`);
  }
  const buffer = await response.arrayBuffer();
  fs.writeFileSync(filepath, Buffer.from(buffer));
}

async function generateImages() {
  const results: { success: string[]; failed: { slug: string; error: string }[] } = {
    success: [],
    failed: [],
  };

  for (const image of images) {
    const filename = `gallery-${image.slug}.png`;
    const filepath = path.join(OUTPUT_DIR, filename);

    console.log(`\n[${images.indexOf(image) + 1}/${images.length}] Generating: ${image.title}...`);

    try {
      const result = await generateImage({
        model: "image-01",
        prompt: image.prompt,
        aspectRatio: "16:9",
      });

      if (result.imageUrls && result.imageUrls.length > 0) {
        await downloadImage(result.imageUrls[0], filepath);
        console.log(`  SUCCESS: Saved to ${filepath}`);
        results.success.push(image.slug);
      } else if (result.base64ImageList && result.base64ImageList.length > 0) {
        const buffer = Buffer.from(result.base64ImageList[0], "base64");
        fs.writeFileSync(filepath, buffer);
        console.log(`  SUCCESS: Saved to ${filepath}`);
        results.success.push(image.slug);
      } else {
        throw new Error("No image URLs or base64 data returned");
      }
    } catch (error) {
      console.log(`  FAILED: ${error instanceof Error ? error.message : "Unknown error"}`);
      results.failed.push({ slug: image.slug, error: error instanceof Error ? error.message : "Unknown error" });
    }

    // Small delay between requests to avoid rate limiting
    await new Promise(resolve => setTimeout(resolve, 1000));
  }

  console.log("\n" + "=".repeat(50));
  console.log("GENERATION COMPLETE");
  console.log("=".repeat(50));
  console.log(`SUCCESS: ${results.success.length} images`);
  console.log(`FAILED: ${results.failed.length} images`);

  if (results.failed.length > 0) {
    console.log("\nFailed images:");
    results.failed.forEach(f => console.log(`  - ${f.slug}: ${f.error}`));
  }

  // Save results to JSON
  fs.writeFileSync(
    path.join(OUTPUT_DIR, "generation-results.json"),
    JSON.stringify(results, null, 2)
  );
  console.log(`\nResults saved to ${OUTPUT_DIR}/generation-results.json`);
}

generateImages().catch(console.error);