import { generateImage } from "../src/ai/images/minimax";
import * as fs from "node:fs";
import * as path from "node:path";
import "dotenv/config";

const OUTPUT_DIR = "public/images";

const images = [
  { slug: "france-eiffel", title: "Eiffel Tower Paris", category: "France", subcategory: "Paris" },
  { slug: "france-lavender", title: "Lavender Field Provence", category: "France", subcategory: "Provence" },
  { slug: "japan-fuji", title: "Mt Fuji Japan", category: "Japan", subcategory: "Fuji" },
  { slug: "japan-cherry", title: "Cherry Blossom Tokyo", category: "Japan", subcategory: "Tokyo" },
  { slug: "japan-forbidden-city", title: "Forbidden City Beijing", category: "China", subcategory: "Beijing" },
  { slug: "china-great-wall", title: "Great Wall Beijing", category: "China", subcategory: "Beijing" },
  { slug: "china-yellow-mountain", title: "Yellow Mountain Anhui", category: "China", subcategory: "Anhui" },
  { slug: "china-zhangjiajie", title: "Zhangjiajie Avatar Mountains", category: "China", subcategory: "Hunan" },
  { slug: "china-guilin", title: "Guilin Karst Mountains", category: "China", subcategory: "Guangxi" },
  { slug: "china-westlake", title: "West Lake Hangzhou", category: "China", subcategory: "Zhejiang" },
  { slug: "netherlands-tulip", title: "Tulip Fields Keukenhof", category: "Netherlands", subcategory: "Keukenhof" },
  { slug: "netherlands-giethoorn", title: "Giethoorn Canal Village", category: "Netherlands", subcategory: "Giethoorn" },
  { slug: "usa-grand-canyon", title: "Grand Canyon Arizona", category: "USA", subcategory: "Arizona" },
  { slug: "usa-yellowstone", title: "Yellowstone Wyoming", category: "USA", subcategory: "Wyoming" },
  { slug: "usa-niagara", title: "Niagara Falls New York", category: "USA", subcategory: "New York" },
  { slug: "italy-colosseum", title: "Colosseum Rome", category: "Italy", subcategory: "Rome" },
  { slug: "spain-sagrada", title: "Sagrada Familia Barcelona", category: "Spain", subcategory: "Barcelona" },
  { slug: "spain-seville", title: "Plaza de España Seville", category: "Spain", subcategory: "Seville" },
  { slug: "norway-fjord", title: "Norwegian Fjord", category: "Norway", subcategory: "Fjord" },
  { slug: "norway-aurora", title: "Northern Lights Norway", category: "Norway", subcategory: "Tromso" },
  { slug: "australia-sydney", title: "Sydney Opera House", category: "Australia", subcategory: "Sydney" },
  { slug: "australia-uluru", title: "Uluru Ayers Rock", category: "Australia", subcategory: "Northern Territory" },
  { slug: "egypt-pyramids", title: "Giza Pyramids Egypt", category: "Egypt", subcategory: "Giza" },
  { slug: "egypt-karnak", title: "Karnak Temple Luxor", category: "Egypt", subcategory: "Luxor" },
  { slug: "india-taj-mahal", title: "Taj Mahal Agra", category: "India", subcategory: "Agra" },
  { slug: "india-jaipur", title: "Hawa Mahal Jaipur", category: "India", subcategory: "Rajasthan" },
  { slug: "jordan-petra", title: "Petra Jordan", category: "Jordan", subcategory: "Petra" },
  { slug: "mexico-chichen", title: "Chichen Itza Mexico", category: "Mexico", subcategory: "Yucatan" },
  { slug: "morocco-marrakech", title: "Jemaa el-Fna Marrakech", category: "Morocco", subcategory: "Marrakech" },
  { slug: "peru-machu", title: "Machu Picchu Peru", category: "Peru", subcategory: "Cusco" },
  { slug: "uae-burj", title: "Burj Khalifa Dubai", category: "UAE", subcategory: "Dubai" },
  { slug: "uae-dubai-mall", title: "Dubai Mall Aquarium", category: "UAE", subcategory: "Dubai" },
  { slug: "sri-lanka-sigiriya", title: "Sigiriya Rock Fortress", category: "Sri Lanka", subcategory: "Sigiriya" },
  { slug: "south-africa-table", title: "Table Mountain Cape Town", category: "South Africa", subcategory: "Cape Town" },
];

const prompts: Record<string, string> = {
  "france-eiffel": "The Eiffel Tower in Paris completely empty of people, bright clear sunny French midday with crystal blue sky, the famous iron lattice tower with its iconic shape, a field or marked position at the Trocadéro gardens where visitors normally stand for photos but currently empty, the grand French monument with the French tricolor flag flying from the top, the Champ de Mars lawn stretching out below, warm Parisian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "france-lavender": "A lavender field in Provence France completely empty of people, bright clear sunny French Mediterranean midday with crystal blue sky, the iconic rolling purple lavender fields stretching to the horizon under brilliant sunlight, a stone pathway or marked position in the field where photographers normally stand but currently empty, the famous French countryside with its medieval villages visible in the distance, the dramatic purple flowers with the Alps in the background, warm fragrant summer air, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "japan-fuji": "Mount Fuji in Japan completely empty of people, bright clear sunny Japanese midday with crystal blue sky, the iconic snow-capped volcanic cone reflected in the calm waters of Lake Kawaguchiko, a lakeside platform or marked position where photographers normally stand for photos but currently empty, the famous Japanese mountain with its perfect symmetrical shape rising above the surrounding forests, cherry blossoms visible in the foreground, warm Japanese sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "japan-cherry": "Cherry blossom trees in Tokyo Japan completely empty of people, bright clear sunny Japanese spring midday with crystal blue sky, the famous pink and white cherry blossom trees lining the path through a traditional Japanese park, a stone path or marked position where visitors normally stand for photos but currently empty, the iconic spring scenery with delicate flower petals falling, the historic Japanese architecture in the background, warm spring sunlight filtering through the blossoms, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty spring landscape no humans",
  "japan-forbidden-city": "The Forbidden City in Beijing China completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous imperial palace with its iconic red walls and golden roof tiles, a stone courtyard or marked position where visitors normally stand for photos but currently empty, the grand imperial architecture with its rows of ornate buildings, the massive bronze urns and stone carvings in the outer court, warm Chinese sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "china-great-wall": "The Great Wall of China near Beijing completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous ancient wall winding over the mountain peaks with its iconic watchtowers, a marked position on the wall or platform where photographers normally stand but currently empty, the dramatic mountain landscape with the wall stretching to the horizon, the historic brick and stone fortifications, warm Chinese sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "china-yellow-mountain": "Yellow Mountain in Anhui China completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous oddly-shaped granite peaks with ancient pine trees clinging to the rocks, a marked viewpoint or platform where photographers normally stand but currently empty, the dramatic stone pillars surrounded by wispy clouds, the legendary Eastern Huangshan scenery with its strange rocks and sea of clouds, warm Chinese mountain light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "china-zhangjiajie": "Zhangjiajie National Forest Park in Hunan China completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous sandstone pillar mountains rising dramatically from the lush forest floor, a marked viewpoint or marked platform where photographers normally stand but currently empty, the dramatic Avatar-like floating mountains with ancient trees growing from the peaks, the glass walkway overlooking the valleys, warm Chinese sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "china-guilin": "Guilin in Guangxi China completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous karst mountains rising from the Li River with their iconic pointed peaks, a marked riverside platform or bamboo boat position where photographers normally stand for photos but currently empty, the poetic Chinese landscape with water buffaloes in the rice paddies, the limestone peaks reflected in the calm river water, warm Chinese southern light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "china-westlake": "West Lake in Hangzhou China completely empty of people, bright clear sunny Chinese midday with crystal blue sky, the famous ancient Chinese lake with its iconic pagodas and causeways, a marked lakeside pavilion or boat position where photographers normally stand for photos but currently empty, the beautiful traditional Chinese gardens with willow trees trailing in the water, the Leifeng Pagoda visible in the distance across the lake, warm Chinese sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "netherlands-tulip": "Tulip fields in Keukenhof Netherlands completely empty of people, bright clear sunny Dutch spring midday with crystal blue sky, the famous colorful tulip fields in full bloom stretching to the horizon, a marked wooden walkway or windmill position where photographers normally stand but currently empty, the iconic Dutch countryside with historic windmills in the background, rows of red pink yellow and purple tulips, warm spring sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "netherlands-giethoorn": "Giethoorn in Netherlands completely empty of people, bright clear sunny Dutch midday with crystal blue sky, the famous car-free canal village with its thatched-roof farmhouses and wooden bridges, a marked boat position or canal-side platform where photographers normally stand but currently empty, the peaceful Dutch waterways with swans and lilies, the rustic fairy-tale village atmosphere, warm Dutch sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty village no humans",
  "usa-grand-canyon": "The Grand Canyon in Arizona USA completely empty of people, bright clear sunny American Southwest midday with crystal blue sky, the famous massive canyon with its colorful layered rock walls carved by the Colorado River, a marked canyon rim viewpoint or marked position where photographers normally stand but currently empty, the dramatic landscape with buttes and mesas visible in the distance, the vast scale of the canyon with the river far below, warm desert sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "usa-yellowstone": "Yellowstone National Park in Wyoming USA completely empty of people, bright clear sunny American Rocky Mountain midday with crystal blue sky, the famous Old Faithful geyser erupting with its tower of white water against the blue sky, a marked wooden boardwalk platform or marked position where visitors normally stand but currently empty, the dramatic geothermal landscape with steaming vents and colorful hot springs in the surrounding pine forest, warm mountain sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty national park no humans",
  "usa-niagara": "Niagara Falls in New York USA completely empty of people, bright clear sunny American midday with crystal blue sky, the famous massive waterfall with its thundering curtain of white water cascading down the cliff, a marked observation deck or boat platform where photographers normally stand but currently empty, the dramatic falls with mist rising from the base, the iconic American Falls and Horseshoe Falls visible, warm summer sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "italy-colosseum": "The Colosseum in Rome Italy completely empty of people, bright clear sunny Italian midday with crystal blue sky, the famous ancient Roman amphitheater with its iconic archways and tiers of seating, a marked position or stone platform where visitors normally stand for photos but currently empty, the remarkable preservation of the historic gladiatorial arena, the Roman Forum visible in the background under the Mediterranean sun, warm Italian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "spain-sagrada": "The Sagrada Familia in Barcelona Spain completely empty of people, bright clear sunny Spanish midday with crystal blue sky, the famous unfinished Gaudi cathedral with its iconic ornate spires reaching to the sky, a marked plaza position or across the street platform where photographers normally stand but currently empty, the dramatic neo-Gothic architecture with its intricate stone carvings and colorful stained glass windows, the massive scale of the basilica visible from below, warm Mediterranean sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "spain-seville": "Plaza de España in Seville Spain completely empty of people, bright clear sunny Spanish midday with crystal blue sky, the famous semi-circular plaza with its iconic tile mosaics and ceramic bridges over the canal, a marked plaza position or stone bench where photographers normally stand but currently empty, the stunning Moorish Revival architecture with its towering brick towers, the historic city of Seville visible beyond the plaza, warm Andalusian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "norway-fjord": "A Norwegian fjord completely empty of people, bright clear sunny Scandinavian midday with crystal blue sky, the famous deep narrow fjord with its dramatic steep rock walls rising from the calm water, a marked ferry boat deck or shore platform where photographers normally stand but currently empty, the iconic Viking landscape with waterfalls cascading down the green mountainsides, a traditional red wooden house village nestled at the water's edge, warm Nordic sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "norway-aurora": "Northern Lights viewing spot in Norway completely empty of people, bright clear sunny Arctic midday with crystal blue sky, a frozen fjord or snow-covered mountain plateau under brilliant winter daylight, a marked platform or frozen lake surface where photographers normally set up tripods but currently empty, the dramatic snow-covered Norwegian landscape with pine forests and frozen waterfalls, the pristine white snow and blue Arctic sky with no aurora visible just brilliant winter light, crisp cold air, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty winter landscape no humans",
  "australia-sydney": "Sydney Opera House in Australia completely empty of people, bright clear sunny Australian midday with crystal blue sky, the famous iconic white shell-shaped roof sails of the opera house jutting out into Sydney Harbour, a marked harbor waterfront platform or marked position where photographers normally stand but currently empty, the dramatic white ceramic tiles of the opera house gleaming in the sunlight, the Sydney Harbour Bridge visible in the background, the blue harbor waters with ferries, warm Australian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "australia-uluru": "Uluru Ayers Rock in Australian outback completely empty of people, bright clear sunny Australian Centralian midday with crystal blue sky, the famous massive red sandstone rock monolith rising from the flat desert plain, a marked viewing platform or marked desert position where visitors normally stand for photos but currently empty, the iconic sacred Aboriginal site with its dramatic color changes from gold to deep red, the surrounding spinifex grass and scrubland, the vast empty red desert stretching to the horizon, warm Outback sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
  "egypt-pyramids": "The Great Pyramids of Giza in Egypt completely empty of people, bright clear sunny Egyptian midday with crystal blue desert sky, the famous ancient pyramids with the Great Pyramid of Khufu towering behind the Sphinx, a marked desert platform or marked position near the Sphinx where visitors normally stand for photos but currently empty, the iconic limestone structures against the golden desert dunes, the Sahara desert stretching to the horizon, the distant figure of the Sphinx, warm Egyptian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "egypt-karnak": "Karnak Temple in Luxor Egypt completely empty of people, bright clear sunny Egyptian midday with crystal blue sky, the famous ancient Egyptian temple complex with its iconic massive columns and avenue of ram-headed sphinxes, a marked temple courtyard or stone platform where visitors normally stand for photos but currently empty, the remarkably preserved hypostyle hall with its towering papyrus-shaped columns, the ancient sacred lake, the desert climate with palm trees, warm Egyptian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty ancient site no humans",
  "india-taj-mahal": "The Taj Mahal in Agra India completely empty of people, bright clear sunny Indian midday with crystal blue sky, the famous white marble mausoleum with its iconic large central dome reflected in the long pool, a marked garden platform or marked position where visitors normally stand for photos but currently empty, the iconic Islamic architecture with its delicate marble inlay work and minarets, the formal Mughal gardens with their symmetric geometric design, warm Indian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "india-jaipur": "Hawa Mahal the Palace of Winds in Jaipur India completely empty of people, bright clear sunny Indian midday with crystal blue sky, the famous iconic pink sandstone building with its 953 small windows designed like a honeycomb, a marked street position or marked platform where photographers normally stand but currently empty, the ornate facade with its delicate lattice windows, the vibrant pink streets of Jaipur old city with bustling markets visible but currently empty, warm Indian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty tourist attraction no humans",
  "jordan-petra": "Petra ancient city in Jordan completely empty of people, bright clear sunny Middle Eastern midday with crystal blue sky, the famous Treasury building carved into the rose-red cliff face with its iconic Hellenistic facade, a marked canyon path or marked position at the treasury where visitors normally stand for photos but currently empty, the dramatic siq canyon with its towering sandstone walls, the ancient Nabataean carved architecture, the rose-red color of the stone glowing in the sunlight, warm desert light, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty ancient site no humans",
  "mexico-chichen": "Chichen Itza in Yucatan Mexico completely empty of people, bright clear sunny Mexican midday with crystal blue tropical sky, the famous El Castillo pyramid with its iconic stepped terraces and Temple of Warriors, a marked plaza position or marked base of the pyramid where visitors normally stand for photos but currently empty, the remarkable restored ancient Maya city with its sacred cenote visible in the distance, the dramatic pyramid shadow and light patterns on the staircase, the surrounding tropical jungle, warm Mayan sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty ancient site no humans",
  "morocco-marrakech": "Jemaa el-Fna square in Marrakech Morocco completely empty of people, bright clear sunny Moroccan midday with crystal blue sky, the famous historic medina square with its iconic minaret of the Koutoubia Mosque rising above the rooftops, a marked roof terrace or marked position in the square where photographers normally stand but currently empty, the vibrant Moroccan cityscape with its ochre-colored buildings and palm trees, the empty famous square that normally buzzes with storytellers and musicians, warm Moroccan sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty city square no humans",
  "peru-machu": "Machu Picchu in Peru completely empty of people, bright clear sunny Peruvian midday with crystal blue sky, the famous ancient Incan citadel perched high on a mountain ridge with its iconic stone temples and terraces, a marked viewpoint or marked position on the terraces where photographers normally stand but currently empty, the dramatic mountain landscape with Huayna Picchu mountain rising behind, the mysterious abandoned city with its precise stonework, the mist sometimes rising from the valley below, warm Andean sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty ancient site no humans",
  "uae-burj": "Burj Khalifa in Dubai UAE completely empty of people, bright clear sunny Middle Eastern midday with crystal blue sky, the famous tallest building in the world with its iconic tapering glass and steel spire rising into the sky, a marked plaza position or marked fountain area where photographers normally stand but currently empty, the dramatic skyscraper with its Islamic geometric patterns in the steel structure, the Dubai Mall and fountains visible below, the desert city skyline, warm Arabian sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty urban landscape no humans",
  "uae-dubai-mall": "Dubai Mall in Dubai UAE completely empty of people, bright clear sunny Middle Eastern midday with crystal blue sky visible through the mall's glass atrium roof, the famous massive Dubai Mall aquarium with its enormous viewing panel and suspended walkway, a marked aquarium viewing position or marked platform where photographers normally stand but currently empty, the stunning underwater world with sharks sea turtles and colorful fish swimming by the giant glass panel, the world's largest shopping mall architecture, warm Dubai sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty mall no humans",
  "sri-lanka-sigiriya": "Sigiriya ancient rock fortress in Sri Lanka completely empty of people, bright clear sunny Sri Lankan midday with crystal blue tropical sky, the famous ancient palace ruins perched atop the massive red rock monolith with its iconic lion paws at the entrance, a marked garden path or marked position at the base where visitors normally stand for photos but currently empty, the dramatic 200-meter high rock with its ancient frescoes and mirror wall, the surrounding lush jungle and sacred mountains, warm Sri Lankan sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty ancient site no humans",
  "south-africa-table": "Table Mountain in Cape Town South Africa completely empty of people, bright clear sunny South African midday with crystal blue sky, the famous flat-topped mountain towering over the city with its iconic tabletop silhouette, a marked viewpoint or marked position on the slopes where photographers normally stand but currently empty, the dramatic mountain landscape with its endemic fynbos vegetation, the Twelve Apostles rock formation visible along the coast, the blue Atlantic Ocean stretching to the horizon, warm African sunlight, eye-level perspective from a standing photographer, 16:9 hyperrealistic travel photography, empty landscape no humans",
};

async function downloadImage(url: string, filepath: string): Promise<void> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to download: ${response.statusText}`);
  const buffer = await response.arrayBuffer();
  fs.writeFileSync(filepath, Buffer.from(buffer));
}

async function retryFailed() {
  const slug = "japan-forbidden-city";
  const filename = `gallery-${slug}.png`;
  const filepath = path.join(OUTPUT_DIR, filename);
  const prompt = prompts[slug];

  console.log(`Retrying: ${slug}...`);
  try {
    const result = await generateImage({ model: "image-01", prompt, aspectRatio: "16:9" });

    if (result.imageUrls?.[0]) {
      await downloadImage(result.imageUrls[0], filepath);
      console.log(`  SUCCESS: ${filepath}`);
    } else if (result.base64ImageList?.[0]) {
      fs.writeFileSync(filepath, Buffer.from(result.base64ImageList[0], "base64"));
      console.log(`  SUCCESS: ${filepath}`);
    } else {
      console.log(`  FAILED: No image returned`);
    }
  } catch (error) {
    console.log(`  FAILED: ${error instanceof Error ? error.message : "Unknown"}`);
  }
}

retryFailed().catch(console.error);